plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bluecat114.run'
    compileSdk 34

    defaultConfig {
        applicationId "com.bluecat114.run"
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "1.3"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lint {
        abortOnError false
    }
}